#!/bin/bash

source ./dependencies.sh

# Need these to run ansible
PLAYBOOK_DEPENDENCIES=("python313-uv" "git")

echo "Checking for missing packages..."

for package in "${PLAYBOOK_DEPENDENCIES[@]}"; do
    if ! zypper se -i "$package" &>/dev/null; then
        echo "Package '$package' is not installed. Installing now..."
        sudo zypper install -y "$package"
        if [ $? -eq 0 ]; then
            echo "Successfully installed '$package'."
        else
            echo "Failed to install '$package'."
        fi
    fi
done

echo "Package check complete."

echo "Checking SSH credentials..."

SSH_READY=check_ssh_key_unlocked
# assume non-present keys will be generated by gh
if [ $SSH_READY == 2 ]; then
    exit 2
fi
eval "$(ssh-agent -s)"
if [ $SSH_READY == 0 ]; then
    ssh-add
fi

echo "Checking connection to GitHub..."

GH_READY=check_github_ssh
if ! "$GH_READY"; then
    setup_gh_cli
    ssh-add
fi

mkdir -p ~/workspace

cd ~/workspace

if [ ! -d "./playbooks/.git" ]; then
    echo "Ansible playbooks repository not found. Cloning..."
    gh repo clone mattwwarren/playbooks
fi
cd playbooks
echo "Updating repo..."
gh repo sync

echo "Starting Ansible bootstrap..."
uv sync
sudo uv run ansible-playbook -i hosts.yaml root.yaml
sudo uv run ansible-playbook -i hosts.yaml me.yaml
