---
- name: Prep for work
  hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Copy vscode repo
    ansible.builtin.copy: 
      src: vscode.repo
      dest: /etc/zypp/repos.d/vscode.repo
      mode: 0444

  - name: Add brave GPG key
    ansible.builtin.rpm_key:
      key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

  - name: Configure brave repo
    community.general.zypper_repository:
      auto_import_keys: true
      repo: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo

  - name: Configure snappy repo
    community.general.zypper_repository:
      auto_import_keys: true
      name: snappy
      repo: https://download.opensuse.org/repositories/system:/snappy/openSUSE_Tumbleweed

  - name: refresh zypper repos
    community.general.zypper_repository:
      runrefresh: true
      repo: "*"

  - name: install core packages
    community.general.zypper:
      name: 
        - git
        - python313-uv
        - python313-pre-commit
        - docker
        - ispell-american
        - code
        - snapd
        - brave-browser
      state: latest

  - name: add me to docker group
    ansible.builtin.user:
      append: true
      name: matthew
      groups:
        - docker

  - name: start snapd apparmor
    ansible.builtin.service:
      name: snapd.apparmor.service
      enabled: true

  - name: start snapd
    ansible.builtin.service:
      name: snapd
      enabled: true
      state: started

  - name: start docker
    ansible.builtin.service:
      name: docker
      enabled: true
      state: started

